// ============================================================
// Mart Studio — Constants & Step Definitions
// ============================================================

import { StepDefinition } from './types';

export const STEPS: StepDefinition[] = [
  {
    id: 1,
    key: 'context',
    title: 'Contexte du produit Data',
    titleShort: 'Contexte',
    icon: '🎯',
    description: 'Définir le contexte, les objectifs et les parties prenantes du Data Product.',
    questions: [
      'Quel est le nom du Data Product ?',
      'Quel problème métier résout-il ?',
      'Quel est son objectif principal ?',
      'Qui sont les utilisateurs de ce produit ?',
      'Quel domaine métier est concerné ?',
      'Qui est le Product Owner ?',
      'Qui est le Data Steward ?',
      'Quelle décision métier ce produit permet-il de prendre ?',
      'À quelle fréquence sera-t-il utilisé ?',
      'Existe-t-il déjà un produit similaire ?',
    ],
  },
  {
    id: 2,
    key: 'concepts',
    title: 'Concepts métiers',
    titleShort: 'Concepts',
    icon: '🧩',
    description: 'Identifier les objets métiers manipulés : entités, événements, références.',
    questions: [
      'Quels sont les principaux objets métiers ?',
      'Quels concepts souhaitez-vous analyser ?',
      'Quels événements souhaitez-vous suivre ?',
      'Quels objets sont créés ?',
      'Quels objets évoluent ?',
      'Quels objets disparaissent ?',
      'Quels sont les concepts de référence ?',
    ],
  },
  {
    id: 3,
    key: 'granularity',
    title: 'Granularité',
    titleShort: 'Granularité',
    icon: '🔬',
    description: 'Définir le niveau de détail et la temporalité des données.',
    questions: [
      "Quelle est l'unité d'observation principale ?",
      'Chaque ligne représente quoi ?',
      'Quel est le niveau de détail attendu ?',
      'Peut-il exister plusieurs lignes pour un même objet ?',
      'Les données sont-elles journalières, mensuelles ou transactionnelles ?',
      'Les données sont-elles historisées ?',
    ],
  },
  {
    id: 4,
    key: 'relations',
    title: 'Relations',
    titleShort: 'Relations',
    icon: '🔗',
    description: 'Définir les liens entre les entités, les cardinalités et les hiérarchies.',
    questions: [
      'Quels objets sont liés ?',
      'Une commande peut-elle exister sans client ?',
      'Un produit peut-il appartenir à plusieurs catégories ?',
      'Une relation est-elle obligatoire ?',
      'Existe-t-il des relations plusieurs-à-plusieurs ?',
      'Quelles sont les cardinalités ?',
      'Existe-t-il des hiérarchies ?',
    ],
  },
  {
    id: 5,
    key: 'attributes',
    title: 'Attributs',
    titleShort: 'Attributs',
    icon: '📋',
    description: 'Détailler les attributs de chaque entité : clés, types, contraintes.',
    questions: [
      'Quels attributs sont nécessaires ?',
      'Quel attribut identifie de manière unique cette entité ?',
      'Existe-t-il une clé naturelle ?',
      'Une clé technique est-elle nécessaire ?',
      'Quels champs sont obligatoires ?',
      'Quels champs sont sensibles ?',
      'Quels champs doivent être historisés ?',
    ],
  },
  {
    id: 6,
    key: 'kpis',
    title: 'Indicateurs',
    titleShort: 'KPIs',
    icon: '📊',
    description: 'Identifier les KPI, les axes d\'analyse et les niveaux d\'agrégation.',
    questions: [
      'Quels KPI souhaitez-vous suivre ?',
      'Comment sont-ils calculés ?',
      'Quelle est leur fréquence ?',
      "Existe-t-il plusieurs niveaux d'agrégation ?",
      'Quels filtres seront utilisés ?',
      "Quels axes d'analyse sont nécessaires ?",
    ],
  },
  {
    id: 7,
    key: 'businessRules',
    title: 'Règles métier',
    titleShort: 'Règles',
    icon: '⚖️',
    description: 'Documenter les règles de gestion, exceptions et contraintes.',
    questions: [
      'Quelles sont les règles de gestion ?',
      'Existe-t-il des exceptions ?',
      'Existe-t-il des contraintes de calcul ?',
      'Existe-t-il des valeurs interdites ?',
      'Existe-t-il des dépendances entre attributs ?',
      'Existe-t-il des règles temporelles ?',
    ],
  },
  {
    id: 8,
    key: 'dataSources',
    title: 'Sources de données',
    titleShort: 'Sources',
    icon: '🗄️',
    description: 'Identifier les origines des données et la stratégie de chargement.',
    questions: [
      "D'où proviennent les données ?",
      'Plusieurs sources sont-elles fusionnées ?',
      'Les données sont-elles fiables ?',
      'Existe-t-il une donnée de référence ?',
      'Les données sont-elles historisées ?',
      'Quelle est la fréquence de chargement ?',
    ],
  },
  {
    id: 9,
    key: 'dataQuality',
    title: 'Qualité des données',
    titleShort: 'Qualité',
    icon: '✅',
    description: 'Définir les contrôles qualité, les seuils et la détection d\'anomalies.',
    questions: [
      'Quels contrôles doivent être réalisés ?',
      'Quelles colonnes doivent être uniques ?',
      'Quelles colonnes sont obligatoires ?',
      'Quels seuils de qualité sont attendus ?',
      'Comment détecter une anomalie ?',
      'Existe-t-il des règles de cohérence ?',
    ],
  },
  {
    id: 10,
    key: 'governance',
    title: 'Gouvernance',
    titleShort: 'Gouvernance',
    icon: '🛡️',
    description: 'Définir la propriété, la confidentialité et la conformité RGPD.',
    questions: [
      'Qui est propriétaire des données ?',
      'Qui valide les définitions ?',
      'Quel est le niveau de confidentialité ?',
      'Existe-t-il des contraintes RGPD ?',
      'Les données sont-elles sensibles ?',
      'Quelle est leur durée de conservation ?',
    ],
  },
  {
    id: 11,
    key: 'architecture',
    title: 'Architecture cible',
    titleShort: 'Architecture',
    icon: '🏗️',
    description: 'Définir la répartition des objets dans l\'architecture data.',
    questions: [
      'Quelles données appartiennent au Datamart ?',
      'Quelles données appartiennent au modèle sémantique ?',
      'Quelles données seront directement exposées dans les rapports ?',
      'Quels objets sont purement techniques ?',
      'Quels objets doivent être documentés dans Collibra ?',
    ],
  },
  {
    id: 12,
    key: 'validation',
    title: 'Validation de la conception',
    titleShort: 'Validation',
    icon: '🏁',
    description: 'Revue automatique, score de maturité et génération des livrables.',
    questions: [],
  },
];

export const MATURITY_DIMENSIONS = [
  { key: 'businessUnderstanding', label: 'Compréhension métier', color: '#00664F' },
  { key: 'modeling', label: 'Modélisation', color: '#10B981' },
  { key: 'documentation', label: 'Documentation', color: '#6366F1' },
  { key: 'governance', label: 'Gouvernance', color: '#F59E0B' },
  { key: 'dataQuality', label: 'Qualité des données', color: '#EF4444' },
  { key: 'architecture', label: 'Architecture', color: '#8B5CF6' },
  { key: 'dadReadiness', label: 'Préparation DAD', color: '#EC4899' },
] as const;

export const APP_CONFIG = {
  name: 'Mart Studio',
  tagline: 'Atelier IA de conception Data Product',
  description: 'Concevez votre Data Product avec l\'accompagnement d\'un Senior Data Architect IA',
  version: '1.0.0',
};
